---
# Source: microservice/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-gateway-microservice
  namespace: dev
  labels:
    helm.sh/chart: microservice-1.0.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: swagger-gateway
    app: swagger-gateway
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    environment: dev
    app: swagger-gateway
    component: api-docs
    tier: infrastructure
  annotations:
    kubernetes.io/ingress.class: "gce"
    cloud.google.com/backend-config: '{"default": "swagger-gateway-microservice-backend-config"}'
    networking.gke.io/managed-certificates: swagger-gateway-microservice-cert
    cloud.google.com/backend-config: '{"default": "swagger-gateway-backend-config"}'
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: swagger-dev-ip
    networking.gke.io/managed-certificates: swagger-gateway-cert
spec:
  rules:
    - host: "swagger.dev.ourritual.com"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: swagger-gateway-microservice
                port:
                  number: 80
