---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: swagger-gateway-microservice
  namespace: dev
  labels:
    helm.sh/chart: microservice-1.0.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: swagger-gateway
    app: swagger-gateway
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    environment: dev
    app: swagger-gateway
    component: api-docs
    tier: infrastructure
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    # Link to BackendConfig for IAP, health checks, etc.
    cloud.google.com/backend-config: '{"default": "swagger-gateway-microservice-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: swagger-gateway
    app: swagger-gateway
